name: MERN STACK APPLICATION

on: 
  push:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: npm install
        env: 
          CI: true

  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.13.15
        with: 
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
